server:
  port: 8080
logging:
  level:
    com.lk.ss1: debug
    org.springframework.security: debug

spring:
  profiles:
    active: dev

info:
  name: "李四"
  message: "酷爱跑酷"
#spring:
#  security:
#    user:
#      name: user
#      password: 12345678